package graph

// Copyright (c) Microsoft and contributors.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

        // Access enumerates the values for access.
    type Access string

    const (
                // Allow ...
        Allow Access = "Allow"
                // Deny ...
        Deny Access = "Deny"
            )
    // PossibleAccessValues returns an array of possible values for the Access const type.
    func PossibleAccessValues() []Access {
        return []Access{Allow,Deny}
    }

        // OperationStatus enumerates the values for operation status.
    type OperationStatus string

    const (
                // Failed ...
        Failed OperationStatus = "Failed"
                // InProgress ...
        InProgress OperationStatus = "InProgress"
                // Succeeded ...
        Succeeded OperationStatus = "Succeeded"
            )
    // PossibleOperationStatusValues returns an array of possible values for the OperationStatus const type.
    func PossibleOperationStatusValues() []OperationStatus {
        return []OperationStatus{Failed,InProgress,Succeeded}
    }

        // ProvisioningState enumerates the values for provisioning state.
    type ProvisioningState string

    const (
                // ProvisioningStateDeleting ...
        ProvisioningStateDeleting ProvisioningState = "Deleting"
                // ProvisioningStateFailed ...
        ProvisioningStateFailed ProvisioningState = "Failed"
                // ProvisioningStateSucceeded ...
        ProvisioningStateSucceeded ProvisioningState = "Succeeded"
                // ProvisioningStateUpdating ...
        ProvisioningStateUpdating ProvisioningState = "Updating"
            )
    // PossibleProvisioningStateValues returns an array of possible values for the ProvisioningState const type.
    func PossibleProvisioningStateValues() []ProvisioningState {
        return []ProvisioningState{ProvisioningStateDeleting,ProvisioningStateFailed,ProvisioningStateSucceeded,ProvisioningStateUpdating}
    }

        // ResourceIdentityType enumerates the values for resource identity type.
    type ResourceIdentityType string

    const (
                // None ...
        None ResourceIdentityType = "None"
                // SystemAssigned ...
        SystemAssigned ResourceIdentityType = "SystemAssigned"
                // SystemAssignedUserAssigned ...
        SystemAssignedUserAssigned ResourceIdentityType = "SystemAssigned, UserAssigned"
                // UserAssigned ...
        UserAssigned ResourceIdentityType = "UserAssigned"
            )
    // PossibleResourceIdentityTypeValues returns an array of possible values for the ResourceIdentityType const type.
    func PossibleResourceIdentityTypeValues() []ResourceIdentityType {
        return []ResourceIdentityType{None,SystemAssigned,SystemAssignedUserAssigned,UserAssigned}
    }

