package graph

// Copyright (c) Microsoft and contributors.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "encoding/json"
    "github.com/Azure/go-autorest/autorest"
    "github.com/Azure/go-autorest/autorest/date"
)

// The package's fully qualified name.
const fqdn = "github.com/Azure/azure-sdk-for-go/services/graph/1.0/graph"

        // AzureAsyncOperationResult the response body contains the status of the specified asynchronous operation,
        // indicating whether it has succeeded, is in progress, or has failed. Note that this status is distinct from
        // the HTTP status code returned for the Get Operation Status operation itself. If the asynchronous operation
        // succeeded, the response body includes the HTTP status code for the successful request. If the asynchronous
        // operation failed, the response body includes the HTTP status code for the failed request and error
        // information regarding the failure.
        type AzureAsyncOperationResult struct {
        // Status - Status of the Azure async operation. Possible values include: 'InProgress', 'Succeeded', 'Failed'
        Status OperationStatus `json:"status,omitempty"`
        // Error - Details of the error occurred during specified asynchronous operation.
        Error *Error `json:"error,omitempty"`
        }

        // CloudError an error response from the service.
        type CloudError struct {
        // Error - Cloud error body.
        Error *CloudErrorBody `json:"error,omitempty"`
        }

        // CloudErrorBody an error response from the service.
        type CloudErrorBody struct {
        // Code - An identifier for the error. Codes are invariant and are intended to be consumed programmatically.
        Code *string `json:"code,omitempty"`
        // Message - A message describing the error, intended to be suitable for display in a user interface.
        Message *string `json:"message,omitempty"`
        // Target - The target of the particular error. For example, the name of the property in error.
        Target *string `json:"target,omitempty"`
        // Details - A list of additional details about the error.
        Details *[]CloudErrorBody `json:"details,omitempty"`
        }

        // CustomMessagePropertiesFormat ...
        type CustomMessagePropertiesFormat struct {
        // MessageLanguage - The language message of the message
        MessageLanguage *string `json:"messageLanguage,omitempty"`
        // CcRecipients - All Cc emails addresses
        CcRecipients *[]CustomMessagePropertiesFormatCcRecipientsItem `json:"ccRecipients,omitempty"`
        // CustomizedMessageBody - The content of the message
        CustomizedMessageBody *string `json:"customizedMessageBody,omitempty"`
        }

        // CustomMessagePropertiesFormatCcRecipientsItem ...
        type CustomMessagePropertiesFormatCcRecipientsItem struct {
        EmailAddress *CustomMessagePropertiesFormatCcRecipientsItemEmailAddress `json:"emailAddress,omitempty"`
        }

        // CustomMessagePropertiesFormatCcRecipientsItemEmailAddress ...
        type CustomMessagePropertiesFormatCcRecipientsItemEmailAddress struct {
        // Name - The name of the recipient
        Name *string `json:"name,omitempty"`
        // Address - The email address of the recipient
        Address *string `json:"address,omitempty"`
        }

        // Error common error representation.
        type Error struct {
        // Code - Error code.
        Code *string `json:"code,omitempty"`
        // Message - Error message.
        Message *string `json:"message,omitempty"`
        // Target - Error target.
        Target *string `json:"target,omitempty"`
        // Details - Error details.
        Details *[]ErrorDetails `json:"details,omitempty"`
        // InnerError - Inner error message.
        InnerError *string `json:"innerError,omitempty"`
        }

        // ErrorDetails common error details representation.
        type ErrorDetails struct {
        // Code - Error code.
        Code *string `json:"code,omitempty"`
        // Target - Error target.
        Target *string `json:"target,omitempty"`
        // Message - Error message.
        Message *string `json:"message,omitempty"`
        }

        // GlobalGraphResource ...
        type GlobalGraphResource struct {
        // ID - READ-ONLY; The ID of the resource
        ID *string `json:"id,omitempty"`
        }

        // MarshalJSON is the custom marshaler for GlobalGraphResource.
        func (ggr GlobalGraphResource)MarshalJSON() ([]byte, error){
        objectMap := make(map[string]interface{})
                return json.Marshal(objectMap)
        }

        // GuestUser ...
        type GuestUser struct {
        autorest.Response `json:"-"`
        // AboutMe - A freeform text entry field for the user to describe themselves.
        AboutMe *string `json:"aboutMe,omitempty"`
        // AccountEnabled - true if the account is enabled; otherwise, false. This property is required when a user is created. Supports $filter.
        AccountEnabled *bool `json:"accountEnabled,omitempty"`
        // AgeGroup - Sets the age group of the user. Allowed values: null, minor, notAdult and adult. Refer to the legal age group property definitions for further information.
        AgeGroup *string `json:"ageGroup,omitempty"`
        // Birthday - The birthday of the user. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like this: '2014-01-01T00:00:00Z'
        Birthday *date.Time `json:"birthday,omitempty"`
        // BusinessPhones - The telephone numbers for the user. NOTE: Although this is a string collection, only one number can be set for this property.
        BusinessPhones *[]string `json:"businessPhones,omitempty"`
        // City - The city in which the user is located. Supports $filter.
        City *string `json:"city,omitempty"`
        // CompanyName - The company name which the user is associated. This property can be useful for describing the company that an external user comes from.
        CompanyName *string `json:"companyName,omitempty"`
        // ConsentProvidedForMinor - Sets whether consent has been obtained for minors. Allowed values: null, granted, denied and notRequired. Refer to the legal age group property definitions for further information.
        ConsentProvidedForMinor *string `json:"consentProvidedForMinor,omitempty"`
        // Country - The country/region in which the user is located; for example, ?US? or ?UK?. Supports $filter.
        Country *string `json:"country,omitempty"`
        // CreatedDateTime - The created date of the user object.
        CreatedDateTime *date.Time `json:"createdDateTime,omitempty"`
        // CreationType - READ-ONLY; Indicates whether the user account was created as a regular school or work account (null), an external account (Invitation), a local account for an Azure Active Directory B2C tenant (LocalAccount) or self-service sign-up using email verification (EmailVerified). Read-only.
        CreationType *string `json:"creationType,omitempty"`
        // DeletedDateTime - The date and time the user was deleted.
        DeletedDateTime *date.Time `json:"deletedDateTime,omitempty"`
        // Department - The name for the department in which the user works. Supports $filter.
        Department *string `json:"department,omitempty"`
        // DisplayName - The name displayed in the address book for the user. This is usually the combination of the user's first name, middle initial and last name. This property is required when a user is created and it cannot be cleared during updates. Supports $filter and $orderby.
        DisplayName *string `json:"displayName,omitempty"`
        // EmployeeID - The employee identifier assigned to the user by the organization. Supports $filter.
        EmployeeID *string `json:"employeeId,omitempty"`
        // ExternalUserState - READ-ONLY; For an external user invited to the tenant using the invitation API, this property represents the invited user's invitation status. For invited users, the state can be PendingAcceptance or Accepted, or null for all other users.
        ExternalUserState *string `json:"externalUserState,omitempty"`
        // ExternalUserStateChangeDateTime - READ-ONLY; Shows the timestamp for the latest change to the externalUserState property.
        ExternalUserStateChangeDateTime *date.Time `json:"externalUserStateChangeDateTime,omitempty"`
        // FaxNumber - The fax number of the user.
        FaxNumber *string `json:"faxNumber,omitempty"`
        // GivenName - The given name (first name) of the user. Supports $filter.
        GivenName *string `json:"givenName,omitempty"`
        // HireDate - The hire date of the user. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like this: '2014-01-01T00:00:00Z'
        HireDate *date.Time `json:"hireDate,omitempty"`
        // ImAddresses - READ-ONLY; The instant message voice over IP (VOIP) session initiation protocol (SIP) addresses for the user. Read-only.
        ImAddresses *[]string `json:"imAddresses,omitempty"`
        // Interests - A list for the user to describe their interests.
        Interests *[]string `json:"interests,omitempty"`
        // IsResourceAccount - Do not use ? reserved for future use.
        IsResourceAccount *bool `json:"isResourceAccount,omitempty"`
        // JobTitle - The user?s job title. Supports $filter.
        JobTitle *string `json:"jobTitle,omitempty"`
        // LastPasswordChangeDateTime - The time when this Azure AD user last changed their password. The date and time information uses ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like this: '2014-01-01T00:00:00Z'
        LastPasswordChangeDateTime *date.Time `json:"lastPasswordChangeDateTime,omitempty"`
        // LegalAgeGroupClassification - READ-ONLY; Used by enterprise applications to determine the legal age group of the user. This property is read-only and calculated based on ageGroup and consentProvidedForMinor properties. Allowed values: null, minorWithOutParentalConsent, minorWithParentalConsent, minorNoParentalConsentRequired, notAdult and adult. Refer to the legal age group property definitions for further information.)
        LegalAgeGroupClassification *string `json:"legalAgeGroupClassification,omitempty"`
        // Mail - READ-ONLY; The SMTP address for the user, for example, "jeff@contoso.onmicrosoft.com". Read-Only. Supports $filter.
        Mail *string `json:"mail,omitempty"`
        // MailNickname - The mail alias for the user. This property must be specified when a user is created. Supports $filter.
        MailNickname *string `json:"mailNickname,omitempty"`
        // MobilePhone - The primary cellular telephone number for the user.
        MobilePhone *string `json:"mobilePhone,omitempty"`
        // MySite - The URL for the user's personal site.
        MySite *string `json:"mySite,omitempty"`
        // OfficeLocation - The office location in the user's place of business.
        OfficeLocation *string `json:"officeLocation,omitempty"`
        // OnPremisesDistinguishedName - READ-ONLY; Contains the on-premises Active Directory distinguished name or DN. The property is only populated for customers who are synchronizing their on-premises directory to Azure Active Directory via Azure AD Connect. Read-only.
        OnPremisesDistinguishedName *string `json:"onPremisesDistinguishedName,omitempty"`
        // OnPremisesDomainName - READ-ONLY; Contains the on-premises domainFQDN, also called dnsDomainName synchronized from the on-premises directory. The property is only populated for customers who are synchronizing their on-premises directory to Azure Active Directory via Azure AD Connect. Read-only.
        OnPremisesDomainName *string `json:"onPremisesDomainName,omitempty"`
        // OnPremisesImmutableID - This property is used to associate an on-premises Active Directory user account to their Azure AD user object. This property must be specified when creating a new user account in the Graph if you are using a federated domain for the user?s userPrincipalName (UPN) property. Important: The $ and _ characters cannot be used when specifying this property. Supports $filter.
        OnPremisesImmutableID *string `json:"onPremisesImmutableId,omitempty"`
        // OnPremisesLastSyncDateTime - READ-ONLY; Indicates the last time at which the object was synced with the on-premises directory; for example: "2013-02-16T03:04:54Z". The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like this: '2014-01-01T00:00:00Z'. Read-only.
        OnPremisesLastSyncDateTime *date.Time `json:"onPremisesLastSyncDateTime,omitempty"`
        // OnPremisesSamAccountName - READ-ONLY; Contains the on-premises samAccountName synchronized from the on-premises directory. The property is only populated for customers who are synchronizing their on-premises directory to Azure Active Directory via Azure AD Connect. Read-only.
        OnPremisesSamAccountName *string `json:"onPremisesSamAccountName,omitempty"`
        // OnPremisesSecurityIdentifier - READ-ONLY; Contains the on-premises security identifier (SID) for the user that was synchronized from on-premises to the cloud. Read-only.
        OnPremisesSecurityIdentifier *string `json:"onPremisesSecurityIdentifier,omitempty"`
        // OnPremisesSyncEnabled - READ-ONLY; true if this object is synced from an on-premises directory; false if this object was originally synced from an on-premises directory but is no longer synced; null if this object has never been synced from an on-premises directory (default). Read-only
        OnPremisesSyncEnabled *bool `json:"onPremisesSyncEnabled,omitempty"`
        // OnPremisesUserPrincipalName - READ-ONLY; Contains the on-premises userPrincipalName synchronized from the on-premises directory. The property is only populated for customers who are synchronizing their on-premises directory to Azure Active Directory via Azure AD Connect. Read-only.
        OnPremisesUserPrincipalName *string `json:"onPremisesUserPrincipalName,omitempty"`
        // OtherMails - A list of additional email addresses for the user; for example: ["bob@contoso.com", "Robert@fabrikam.com"]. Supports $filter.
        OtherMails *string `json:"otherMails,omitempty"`
        // PasswordPolicies - Specifies password policies for the user. This value is an enumeration with one possible value being ?DisableStrongPassword?, which allows weaker passwords than the default policy to be specified. ?DisablePasswordExpiration? can also be specified. The two may be specified together; for example: "DisablePasswordExpiration, DisableStrongPassword".
        PasswordPolicies *string `json:"passwordPolicies,omitempty"`
        // PastProjects - A list for the user to enumerate their past projects.
        PastProjects *[]string `json:"pastProjects,omitempty"`
        // PostalCode - The postal code for the user's postal address. The postal code is specific to the user's country/region. In the United States of America, this attribute contains the ZIP code.
        PostalCode *string `json:"postalCode,omitempty"`
        // PreferredDataLocation - The preferred data location for the user. For more information, see OneDrive Online Multi-Geo.
        PreferredDataLocation *string `json:"preferredDataLocation,omitempty"`
        // PreferredLanguage - The preferred language for the user. Should follow ISO 639-1 Code; for example "en-US".
        PreferredLanguage *string `json:"preferredLanguage,omitempty"`
        // PreferredName - The preferred name for the user.
        PreferredName *string `json:"preferredName,omitempty"`
        // ProxyAddresses - READ-ONLY; For example: ["SMTP: bob@contoso.com", "smtp: bob@sales.contoso.com"] The any operator is required for filter expressions on multi-valued properties. Read-only, Not nullable. Supports $filter.
        ProxyAddresses *[]string `json:"proxyAddresses,omitempty"`
        // RefreshTokensValidFromDateTime - READ-ONLY; Any refresh tokens or sessions tokens (session cookies) issued before this time are invalid, and applications will get an error when using an invalid refresh or sessions token to acquire a delegated access token (to access APIs such as Microsoft Graph). If this happens, the application will need to acquire a new refresh token by making a request to the authorize endpoint.
        RefreshTokensValidFromDateTime *date.Time `json:"refreshTokensValidFromDateTime,omitempty"`
        // Responsibilities - A list for the user to enumerate their responsibilities.
        Responsibilities *[]string `json:"responsibilities,omitempty"`
        // Schools - A list for the user to enumerate the schools they have attended.
        Schools *[]string `json:"schools,omitempty"`
        // ShowInAddressList - true if the Outlook global address list should contain this user, otherwise false. If not set, this will be treated as true. For users invited through the invitation manager, this property will be set to false.
        ShowInAddressList *bool `json:"showInAddressList,omitempty"`
        // Skills - A list for the user to enumerate their skills.
        Skills *[]string `json:"skills,omitempty"`
        // SignInSessionsValidFromDateTime - READ-ONLY; Any refresh tokens or sessions tokens (session cookies) issued before this time are invalid, and applications will get an error when using an invalid refresh or sessions token to acquire a delegated access token (to access APIs such as Microsoft Graph). If this happens, the application will need to acquire a new refresh token by making a request to the authorize endpoint. Read-only. Use revokeSignInSessions to reset.
        SignInSessionsValidFromDateTime *date.Time `json:"signInSessionsValidFromDateTime,omitempty"`
        // State - The state or province in the user's address. Supports $filter.
        State *string `json:"state,omitempty"`
        // StreetAddress - The street address of the user's place of business.
        StreetAddress *string `json:"streetAddress,omitempty"`
        // Surname - The user's surname (family name or last name). Supports $filter.
        Surname *string `json:"surname,omitempty"`
        // UsageLocation - A two letter country code (ISO standard 3166). Required for users that will be assigned licenses due to legal requirement to check for availability of services in countries. Examples include: "US", "JP", and "GB". Not nullable. Supports $filter.
        UsageLocation *string `json:"usageLocation,omitempty"`
        // UserPrincipalName - The user principal name (UPN) of the user. The UPN is an Internet-style login name for the user based on the Internet standard RFC 822. By convention, this should map to the user's email name. The general format is alias@domain, where domain must be present in the tenant?s collection of verified domains. This property is required when a user is created. The verified domains for the tenant can be accessed from the verifiedDomains property of organization. Supports $filter and $orderby.
        UserPrincipalName *string `json:"userPrincipalName,omitempty"`
        // UserType - A string value that can be used to classify user types in your directory, such as ?Member? and ?Guest?. Supports $filter.
        UserType *string `json:"userType,omitempty"`
        // ID - READ-ONLY; The ID of the resource
        ID *string `json:"id,omitempty"`
        }

        // MarshalJSON is the custom marshaler for GuestUser.
        func (gu GuestUser)MarshalJSON() ([]byte, error){
        objectMap := make(map[string]interface{})
                if(gu.AboutMe != nil) {
                objectMap["aboutMe"] = gu.AboutMe
                }
                if(gu.AccountEnabled != nil) {
                objectMap["accountEnabled"] = gu.AccountEnabled
                }
                if(gu.AgeGroup != nil) {
                objectMap["ageGroup"] = gu.AgeGroup
                }
                if(gu.Birthday != nil) {
                objectMap["birthday"] = gu.Birthday
                }
                if(gu.BusinessPhones != nil) {
                objectMap["businessPhones"] = gu.BusinessPhones
                }
                if(gu.City != nil) {
                objectMap["city"] = gu.City
                }
                if(gu.CompanyName != nil) {
                objectMap["companyName"] = gu.CompanyName
                }
                if(gu.ConsentProvidedForMinor != nil) {
                objectMap["consentProvidedForMinor"] = gu.ConsentProvidedForMinor
                }
                if(gu.Country != nil) {
                objectMap["country"] = gu.Country
                }
                if(gu.CreatedDateTime != nil) {
                objectMap["createdDateTime"] = gu.CreatedDateTime
                }
                if(gu.DeletedDateTime != nil) {
                objectMap["deletedDateTime"] = gu.DeletedDateTime
                }
                if(gu.Department != nil) {
                objectMap["department"] = gu.Department
                }
                if(gu.DisplayName != nil) {
                objectMap["displayName"] = gu.DisplayName
                }
                if(gu.EmployeeID != nil) {
                objectMap["employeeId"] = gu.EmployeeID
                }
                if(gu.FaxNumber != nil) {
                objectMap["faxNumber"] = gu.FaxNumber
                }
                if(gu.GivenName != nil) {
                objectMap["givenName"] = gu.GivenName
                }
                if(gu.HireDate != nil) {
                objectMap["hireDate"] = gu.HireDate
                }
                if(gu.Interests != nil) {
                objectMap["interests"] = gu.Interests
                }
                if(gu.IsResourceAccount != nil) {
                objectMap["isResourceAccount"] = gu.IsResourceAccount
                }
                if(gu.JobTitle != nil) {
                objectMap["jobTitle"] = gu.JobTitle
                }
                if(gu.LastPasswordChangeDateTime != nil) {
                objectMap["lastPasswordChangeDateTime"] = gu.LastPasswordChangeDateTime
                }
                if(gu.MailNickname != nil) {
                objectMap["mailNickname"] = gu.MailNickname
                }
                if(gu.MobilePhone != nil) {
                objectMap["mobilePhone"] = gu.MobilePhone
                }
                if(gu.MySite != nil) {
                objectMap["mySite"] = gu.MySite
                }
                if(gu.OfficeLocation != nil) {
                objectMap["officeLocation"] = gu.OfficeLocation
                }
                if(gu.OnPremisesImmutableID != nil) {
                objectMap["onPremisesImmutableId"] = gu.OnPremisesImmutableID
                }
                if(gu.OtherMails != nil) {
                objectMap["otherMails"] = gu.OtherMails
                }
                if(gu.PasswordPolicies != nil) {
                objectMap["passwordPolicies"] = gu.PasswordPolicies
                }
                if(gu.PastProjects != nil) {
                objectMap["pastProjects"] = gu.PastProjects
                }
                if(gu.PostalCode != nil) {
                objectMap["postalCode"] = gu.PostalCode
                }
                if(gu.PreferredDataLocation != nil) {
                objectMap["preferredDataLocation"] = gu.PreferredDataLocation
                }
                if(gu.PreferredLanguage != nil) {
                objectMap["preferredLanguage"] = gu.PreferredLanguage
                }
                if(gu.PreferredName != nil) {
                objectMap["preferredName"] = gu.PreferredName
                }
                if(gu.Responsibilities != nil) {
                objectMap["responsibilities"] = gu.Responsibilities
                }
                if(gu.Schools != nil) {
                objectMap["schools"] = gu.Schools
                }
                if(gu.ShowInAddressList != nil) {
                objectMap["showInAddressList"] = gu.ShowInAddressList
                }
                if(gu.Skills != nil) {
                objectMap["skills"] = gu.Skills
                }
                if(gu.State != nil) {
                objectMap["state"] = gu.State
                }
                if(gu.StreetAddress != nil) {
                objectMap["streetAddress"] = gu.StreetAddress
                }
                if(gu.Surname != nil) {
                objectMap["surname"] = gu.Surname
                }
                if(gu.UsageLocation != nil) {
                objectMap["usageLocation"] = gu.UsageLocation
                }
                if(gu.UserPrincipalName != nil) {
                objectMap["userPrincipalName"] = gu.UserPrincipalName
                }
                if(gu.UserType != nil) {
                objectMap["userType"] = gu.UserType
                }
                return json.Marshal(objectMap)
        }

        // Invitation ...
        type Invitation struct {
        autorest.Response `json:"-"`
        // ID - READ-ONLY; The ID of the resource
        ID *string `json:"id,omitempty"`
        // InvitedUserEmailAddress - The email of the GuestUser invited
        InvitedUserEmailAddress *string `json:"invitedUserEmailAddress,omitempty"`
        // InvitedUserDisplayName - The name of the GestUser invited
        InvitedUserDisplayName *string `json:"invitedUserDisplayName,omitempty"`
        // SendInvitationMessage - Set to true if there is a custom message in the invitation of the GuestUser
        SendInvitationMessage *bool `json:"sendInvitationMessage,omitempty"`
        // CustomMessagePropertiesFormat - The custom message information for the GuestUser invited
        *CustomMessagePropertiesFormat `json:"invitedUserMessageInfo,omitempty"`
        // InviteRedirectURL - The redirect url for this GuestUser invitation
        InviteRedirectURL *string `json:"inviteRedirectUrl,omitempty"`
        // InviteRedeemURL - The invitation url for this GuestUser invitation
        InviteRedeemURL *string `json:"inviteRedeemUrl,omitempty"`
        // Status - The status of this GuestUser invitation
        Status *string `json:"status,omitempty"`
        InvitedUser *GlobalGraphResource `json:"invitedUser,omitempty"`
        }

        // MarshalJSON is the custom marshaler for Invitation.
        func (i Invitation)MarshalJSON() ([]byte, error){
        objectMap := make(map[string]interface{})
                if(i.InvitedUserEmailAddress != nil) {
                objectMap["invitedUserEmailAddress"] = i.InvitedUserEmailAddress
                }
                if(i.InvitedUserDisplayName != nil) {
                objectMap["invitedUserDisplayName"] = i.InvitedUserDisplayName
                }
                if(i.SendInvitationMessage != nil) {
                objectMap["sendInvitationMessage"] = i.SendInvitationMessage
                }
                if(i.CustomMessagePropertiesFormat != nil) {
                objectMap["invitedUserMessageInfo"] = i.CustomMessagePropertiesFormat
                }
                if(i.InviteRedirectURL != nil) {
                objectMap["inviteRedirectUrl"] = i.InviteRedirectURL
                }
                if(i.InviteRedeemURL != nil) {
                objectMap["inviteRedeemUrl"] = i.InviteRedeemURL
                }
                if(i.Status != nil) {
                objectMap["status"] = i.Status
                }
                if(i.InvitedUser != nil) {
                objectMap["invitedUser"] = i.InvitedUser
                }
                return json.Marshal(objectMap)
        }
        // UnmarshalJSON is the custom unmarshaler for Invitation struct.
        func (i *Invitation) UnmarshalJSON(body []byte) error {
        var m map[string]*json.RawMessage
        err := json.Unmarshal(body, &m)
        if err != nil {
        return err
        }
        for k, v := range  m {
        switch k {
                case "id":
    if v != nil {
        var ID string
        err = json.Unmarshal(*v, &ID)
        if err != nil {
    return err
    }
        i.ID = &ID
    }
                case "invitedUserEmailAddress":
    if v != nil {
        var invitedUserEmailAddress string
        err = json.Unmarshal(*v, &invitedUserEmailAddress)
        if err != nil {
    return err
    }
        i.InvitedUserEmailAddress = &invitedUserEmailAddress
    }
                case "invitedUserDisplayName":
    if v != nil {
        var invitedUserDisplayName string
        err = json.Unmarshal(*v, &invitedUserDisplayName)
        if err != nil {
    return err
    }
        i.InvitedUserDisplayName = &invitedUserDisplayName
    }
                case "sendInvitationMessage":
    if v != nil {
        var sendInvitationMessage bool
        err = json.Unmarshal(*v, &sendInvitationMessage)
        if err != nil {
    return err
    }
        i.SendInvitationMessage = &sendInvitationMessage
    }
                case "invitedUserMessageInfo":
    if v != nil {
        var customMessagePropertiesFormat CustomMessagePropertiesFormat
        err = json.Unmarshal(*v, &customMessagePropertiesFormat)
        if err != nil {
    return err
    }
        i.CustomMessagePropertiesFormat = &customMessagePropertiesFormat
    }
                case "inviteRedirectUrl":
    if v != nil {
        var inviteRedirectURL string
        err = json.Unmarshal(*v, &inviteRedirectURL)
        if err != nil {
    return err
    }
        i.InviteRedirectURL = &inviteRedirectURL
    }
                case "inviteRedeemUrl":
    if v != nil {
        var inviteRedeemURL string
        err = json.Unmarshal(*v, &inviteRedeemURL)
        if err != nil {
    return err
    }
        i.InviteRedeemURL = &inviteRedeemURL
    }
                case "status":
    if v != nil {
        var status string
        err = json.Unmarshal(*v, &status)
        if err != nil {
    return err
    }
        i.Status = &status
    }
                case "invitedUser":
    if v != nil {
        var invitedUser GlobalGraphResource
        err = json.Unmarshal(*v, &invitedUser)
        if err != nil {
    return err
    }
        i.InvitedUser = &invitedUser
    }
            }
        }

        return nil
        }

        // InvitationSended ...
        type InvitationSended struct {
        // InvitedUserEmailAddress - The email of the GuestUser invited
        InvitedUserEmailAddress *string `json:"invitedUserEmailAddress,omitempty"`
        // InvitedUserDisplayName - The name of the GestUser invited
        InvitedUserDisplayName *string `json:"invitedUserDisplayName,omitempty"`
        // SendInvitationMessage - Set to true if there is a custom message in the invitation of the GuestUser
        SendInvitationMessage *bool `json:"sendInvitationMessage,omitempty"`
        // CustomMessagePropertiesFormat - The custom message information for the GuestUser invited
        *CustomMessagePropertiesFormat `json:"invitedUserMessageInfo,omitempty"`
        // InviteRedirectURL - The redirect url for this GuestUser invitation
        InviteRedirectURL *string `json:"inviteRedirectUrl,omitempty"`
        }

        // MarshalJSON is the custom marshaler for InvitationSended.
        func (is InvitationSended)MarshalJSON() ([]byte, error){
        objectMap := make(map[string]interface{})
                if(is.InvitedUserEmailAddress != nil) {
                objectMap["invitedUserEmailAddress"] = is.InvitedUserEmailAddress
                }
                if(is.InvitedUserDisplayName != nil) {
                objectMap["invitedUserDisplayName"] = is.InvitedUserDisplayName
                }
                if(is.SendInvitationMessage != nil) {
                objectMap["sendInvitationMessage"] = is.SendInvitationMessage
                }
                if(is.CustomMessagePropertiesFormat != nil) {
                objectMap["invitedUserMessageInfo"] = is.CustomMessagePropertiesFormat
                }
                if(is.InviteRedirectURL != nil) {
                objectMap["inviteRedirectUrl"] = is.InviteRedirectURL
                }
                return json.Marshal(objectMap)
        }
        // UnmarshalJSON is the custom unmarshaler for InvitationSended struct.
        func (is *InvitationSended) UnmarshalJSON(body []byte) error {
        var m map[string]*json.RawMessage
        err := json.Unmarshal(body, &m)
        if err != nil {
        return err
        }
        for k, v := range  m {
        switch k {
                case "invitedUserEmailAddress":
    if v != nil {
        var invitedUserEmailAddress string
        err = json.Unmarshal(*v, &invitedUserEmailAddress)
        if err != nil {
    return err
    }
        is.InvitedUserEmailAddress = &invitedUserEmailAddress
    }
                case "invitedUserDisplayName":
    if v != nil {
        var invitedUserDisplayName string
        err = json.Unmarshal(*v, &invitedUserDisplayName)
        if err != nil {
    return err
    }
        is.InvitedUserDisplayName = &invitedUserDisplayName
    }
                case "sendInvitationMessage":
    if v != nil {
        var sendInvitationMessage bool
        err = json.Unmarshal(*v, &sendInvitationMessage)
        if err != nil {
    return err
    }
        is.SendInvitationMessage = &sendInvitationMessage
    }
                case "invitedUserMessageInfo":
    if v != nil {
        var customMessagePropertiesFormat CustomMessagePropertiesFormat
        err = json.Unmarshal(*v, &customMessagePropertiesFormat)
        if err != nil {
    return err
    }
        is.CustomMessagePropertiesFormat = &customMessagePropertiesFormat
    }
                case "inviteRedirectUrl":
    if v != nil {
        var inviteRedirectURL string
        err = json.Unmarshal(*v, &inviteRedirectURL)
        if err != nil {
    return err
    }
        is.InviteRedirectURL = &inviteRedirectURL
    }
            }
        }

        return nil
        }

        // ManagedServiceIdentity identity for the resource.
        type ManagedServiceIdentity struct {
        // PrincipalID - READ-ONLY; The principal id of the system assigned identity. This property will only be provided for a system assigned identity.
        PrincipalID *string `json:"principalId,omitempty"`
        // TenantID - READ-ONLY; The tenant id of the system assigned identity. This property will only be provided for a system assigned identity.
        TenantID *string `json:"tenantId,omitempty"`
        // Type - The type of identity used for the resource. The type 'SystemAssigned, UserAssigned' includes both an implicitly created identity and a set of user assigned identities. The type 'None' will remove any identities from the virtual machine. Possible values include: 'SystemAssigned', 'UserAssigned', 'SystemAssignedUserAssigned', 'None'
        Type ResourceIdentityType `json:"type,omitempty"`
        // UserAssignedIdentities - The list of user identities associated with resource. The user identity dictionary key references will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}'.
        UserAssignedIdentities map[string]*ManagedServiceIdentityUserAssignedIdentitiesValue `json:"userAssignedIdentities"`
        }

        // MarshalJSON is the custom marshaler for ManagedServiceIdentity.
        func (msi ManagedServiceIdentity)MarshalJSON() ([]byte, error){
        objectMap := make(map[string]interface{})
                if(msi.Type != "") {
                objectMap["type"] = msi.Type
                }
                if(msi.UserAssignedIdentities != nil) {
                objectMap["userAssignedIdentities"] = msi.UserAssignedIdentities
                }
                return json.Marshal(objectMap)
        }

        // ManagedServiceIdentityUserAssignedIdentitiesValue ...
        type ManagedServiceIdentityUserAssignedIdentitiesValue struct {
        // PrincipalID - READ-ONLY; The principal id of user assigned identity.
        PrincipalID *string `json:"principalId,omitempty"`
        // ClientID - READ-ONLY; The client id of user assigned identity.
        ClientID *string `json:"clientId,omitempty"`
        }

        // MarshalJSON is the custom marshaler for ManagedServiceIdentityUserAssignedIdentitiesValue.
        func (msiAiv ManagedServiceIdentityUserAssignedIdentitiesValue)MarshalJSON() ([]byte, error){
        objectMap := make(map[string]interface{})
                return json.Marshal(objectMap)
        }

